
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtop.h"

/*
* The configuration table for devices
*/

XTop_Config XTop_ConfigTable[XPAR_XTOP_NUM_INSTANCES] =
{
	{
		XPAR_TOP_0_DEVICE_ID,
		XPAR_TOP_0_S_AXI_CTRL_BASEADDR
	}
};


