# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/y/works/vivado/project_1_int16_pp/project_1_int16_pp.srcs/sources_1/bd/top/ip/top_auto_pc_4/top_auto_pc_4.xci
# IP: The module: 'top_auto_pc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/y/works/vivado/project_1_int16_pp/project_1_int16_pp.gen/sources_1/bd/top/ip/top_auto_pc_4/top_auto_pc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_auto_pc_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/y/works/vivado/project_1_int16_pp/project_1_int16_pp.srcs/sources_1/bd/top/ip/top_auto_pc_4/top_auto_pc_4.xci
# IP: The module: 'top_auto_pc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/y/works/vivado/project_1_int16_pp/project_1_int16_pp.gen/sources_1/bd/top/ip/top_auto_pc_4/top_auto_pc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_auto_pc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
