# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_top_0_0/top_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_top_0_0 || ORIG_REF_NAME==top_top_0_0} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# IP: bd/top/ip/top_ps7_0_axi_periph_0/top_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ps7_0_axi_periph_0 || ORIG_REF_NAME==top_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_clk_wiz_0_100M_0/top_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==top_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_1/top_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_1 || ORIG_REF_NAME==top_auto_pc_1} -quiet] -quiet

# IP: bd/top/ip/top_axi_mem_intercon_0/top_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_mem_intercon_0 || ORIG_REF_NAME==top_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_2/top_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_2 || ORIG_REF_NAME==top_auto_pc_2} -quiet] -quiet

# IP: bd/top/ip/top_axi_mem_intercon_1_0/top_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_mem_intercon_1_0 || ORIG_REF_NAME==top_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_3/top_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_3 || ORIG_REF_NAME==top_auto_pc_3} -quiet] -quiet

# IP: bd/top/ip/top_axi_mem_intercon_2_0/top_axi_mem_intercon_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_mem_intercon_2_0 || ORIG_REF_NAME==top_axi_mem_intercon_2_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_4/top_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_4 || ORIG_REF_NAME==top_auto_pc_4} -quiet] -quiet

# IP: bd/top/ip/top_axi_mem_intercon_3_0/top_axi_mem_intercon_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_mem_intercon_3_0 || ORIG_REF_NAME==top_axi_mem_intercon_3_0} -quiet] -quiet

# XDC: /home/y/works/vivado/project_1_int16_pp/project_1_int16_pp.gen/sources_1/bd/top/top_ooc.xdc
